name: Release on Tag Push

on:
  push:
    tags:
      - "v*"

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure dependencies
      run: |
        git submodule init
        git submodule update
        sudo apt-get update
        sudo apt-get install libgit2-dev
    
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


    - name: Package
      run: |
        mkdir -p ${{github.workspace}}/release
        cp ${{github.workspace}}/build/src/today ${{github.workspace}}/release
        cd ${{github.workspace}}/release
        tar -czvf today.tar.gz today

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        files: ${{github.workspace}}/release/today.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
    